chore(continuous.yaml): adds deploy workflow
inloco/incognia-python pull request #15
Opened 2022-04-29 20:20 UTC by joseviccruz

2022-05-06 20:49 UTC, joaoaab approved these changes

2022-05-10 18:11 UTC, t0rr3sp3dr0 requested changes
Let's also move `continuous.yml` to `continuous.yaml`.

2022-05-10 18:34 UTC, joseviccruz commented on setup.cfg
> +python_requires = >= 3.8
We are using features that requires Python 3.8, at least

2022-05-10 18:46 UTC, joseviccruz commented on .github/workflows/continuous.yml
>          python-version: [ 3.8, 3.9 ]
https://github.com/inloco/incognia-python/pull/15#discussion_r869554353

2022-05-13 17:12 UTC, t0rr3sp3dr0 approved these changes

2022-05-16 18:13 UTC, merged